### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gdbaldw** [the729/go-libra#1]
New to golang, so installation instructions would be helpful. After installing golang, from the command line enter: 'go get github.com/the729/go-libra/...' The executables will be placed in $GOPATH/bin/, and when running the executable it needs a copy of the file 'trusted_peers.config.toml' to be in the parent directory, (../trusted_peers.config.toml).

**Comment by the729** [comment]
Thank you for your suggestion. I added a installation section in the readme.

`go-libra` is a library for other developers to build their own projects with. By default, it does not produce any executables in $GOPATH/bin. 

In all examples, `trustedPeersFile` is relative to the example directories. If you are importing `go-libra` in your project, you can freely choose where to put the file. 

Hope this answers your question.
