### ISSUE TITLE
[Bug report] gopherjs-libra doesn't consist with go-libra version.

### ISSUE THREAD

**Issue by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [the729/go-libra#11]
The newest gopherjs-libra lib errors as `Error:  rpc error: code = Unknown desc = Response closed without headers` with the `example` folders code and the server `http://hk2.wutj.info:38080`, while the go-libra performs as well.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
And such as querying an account's state with my libra server I got:

```js
Error:  TypeError: r.getBalance is not a function
```

**Comment by the729** [comment]
Sorry, my proxy was down yesterday, and it is back online now. 

You can also setup your own proxy using docker:
```
docker run -d --name envoy-libra -p 38080:8080 wutianji/envoy-libra
```

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> Sorry, my proxy was down yesterday, and it is back online now.
> 
> You can also setup your own proxy using docker:
> 
> ```
> docker run -d --name envoy-libra -p 38080:8080 wutianji/envoy-libra
> ```

Another broken appeared (running query_account.js):

```js
Address:  18b553473df736e5e363e7214bd624735ca66ac22a7048e3295c9b9b9adfc26a
Error:  TypeError: r.getBalance is not a function
```

**Comment by the729** [comment]
The nodejs example is fixed.
