### ISSUE TITLE
RotateKeys not working

### ISSUE THREAD

**Issue by philsippl** [the729/go-libra#13]
I've tried to make the RotateKeys function working, but there seems to be problems regarding the passing of byte arrays. This is what I tried to pass as the payload of a raw transaction (key is a `[]byte` slice):

```
payload := &types.TxnPayloadScript{
    Code: stdscript.RotateAuthKey,
    Args: []types.TransactionArgument{
        types.TxnArgBytes(key),
    },
}
```

Could you try to verify if RotateKeys is working for you or the problem is related to libra core?

**Comment by the729** [comment]
The testnet was updated. 

Problem should be fixed with the latest master branch. Please have a try.

**Comment by the729** [comment]
Closed. Feel free to reopen if there is still problems.
