### ISSUE TITLE
 Wallet has test.3 migrated to test.4 has changed

### ISSUE THREAD

**Issue by QuincySx** [the729/go-libra#2]

**Comment by the729** [comment]
Can you please elaborate?

**Comment by QuincySx** [comment]
1. The LCS has entered the testing environment?
2. The purse to upgrade to the test4 what needs to change?
3. In your transfer example I didn't see any change?

the729 thank you.

**Comment by the729** [comment]
1. LCS is standarized recently. Prior to that, the legacy canonical serialization was already used. I recently updated go-libra to use standard LCS, which is implemented in a separate package (github.com/the729/lcs)

2. I'm not quite sure what you mean by test4. Is it the testnet update on Sep. 4th? There are some changes regarding serialization (i.e. LCS). But I'd say the most significant change is access path (now replaced with a hash key) in transaction output events. 

3. I don't see any problem making transaction using the latest go-libra example. Which example are you using? (cli_client or p2p_transaction?) What's the output? 

p.s. Please note that github issues are meant to tracking issues with the go-libra package. Discussion that is not related to go-libra package should go to the forum (community.libra.org).
