### ISSUE TITLE
[Options] Need option for customized local node genesis hash.

### ISSUE THREAD

**Issue by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [the729/go-libra#5]
Currently, the genesis hash is hard coded:

```go
genesisHash, _ := hex.DecodeString("b7712506940af39e57de4a868c15849ab09bd8e3c4a89113a492797c6f98bf6b")
```

I think the genesisHash is represented as libra testnet genesis hash.
Are there any options for replacing it to a customized local node hash, not the libra testnet hash?

**Comment by the729** [comment]
The hardcoded genesis hash is kind of a default value. It's there to make sure that all crypto verifications are enabled by default. 

You can set your own genesis hash by calling `SetKnownVersion` right after creating a client instance. The genesis hash is actually the version 0 of the ledger.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> The hardcoded genesis hash is kind of a default value. It's there to make sure that all crypto verifications are enabled by default.
> 
> You can set your own genesis hash by calling `SetKnownVersion` right after creating a client instance. The genesis hash is actually the version 0 of the ledger.

Yes. I'll try later and update.

**Comment by the729** [comment]
I have to say that it's not very trivial to get the genesis hash. I did it by first disabling the consistancy check and querying for txn #0, using the included example/cli_client.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> I have to say that it's not very trivial to get the genesis hash. I did it by first disabling the consistancy check and querying for txn #0, using the included example/cli_client.

Yes I actually did adjust the libra source code and let it print and save the genesis hash from the init_genesis function when I start the libra-swarm node.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
Considering the customization and scalability, why don't we initialize the client with the root hash? If not specified, the root hash is default to testnet hash.

> func New(ServerAddr, TrustedPeer string, RootHash ...string) (*Client, error) {

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
The new function would look like:

```go
func New(ServerAddr, TrustedPeer string, RootHash ...string) (*Client, error) {
	c := &Client{}
	if err := c.loadTrustedPeers(TrustedPeer); err != nil {
		return nil, err
	}
	if err := c.connect(ServerAddr); err != nil {
		return nil, err
	}
	if len(RootHash) == 0 {
		RootHash = append(RootHash, TestNetRootHash)
	}

	genesisHash, _ := hex.DecodeString(RootHash[0])
	c.acc = &accumulator.Accumulator{
		Hasher:             sha3libra.NewTransactionAccumulator(),
		FrozenSubtreeRoots: [][]byte{genesisHash},
		NumLeaves:          1,
	}

	return c, nil
}
```

I would like to pr this version of change if accepted.

**Comment by the729** [comment]
I like the idea of having a more complete configuration when creating a client instance. 

However, personally I don't like using `...string` to define an optional argument. It breaks the strict compile-time type check to some extent. 

I'd prefer to define a `Config` struct which contains all the possible configuration options. Something like `github.com/Shopify/sarama` does: https://github.com/Shopify/sarama/blob/master/config.go

`Config` could include:
- ServerAddr string
- TrustedPeers TOML filename or TOML content or list of public keys
- KnownVersion and Subtrees, either value or TOML filename

Please note that genesis hash is just a special case of known version. We should be able to define any known version other than 0. 

p.s. Breaking the API is not an issue at this time, as libra itself is not stable.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> I like the idea of having a more complete configuration when creating a client instance.
> 
> However, personally I don't like using `...string` to define an optional argument. It breaks the strict compile-time type check to some extent.
> 
> I'd prefer to define a `Config` struct which contains all the possible configuration options. Something like `github.com/Shopify/sarama` does: https://github.com/Shopify/sarama/blob/master/config.go
> 
> `Config` could include:
> 
> * ServerAddr string
> * TrustedPeers TOML filename or TOML content or list of public keys
> * KnownVersion and Subtrees, either value or TOML filename
> 
> Please note that genesis hash is just a special case of known version. We should be able to define any known version other than 0.
> 
> p.s. Breaking the API is not an issue at this time, as libra itself is not stable.

It seems that you already have the  `TrustedPeers  Config` in the config folder. Therefore I could add ServerAddr config or KnownVersion and Subtrees config instead of a stand alone genesis hash.

**Comment by the729** [comment]
I found the set of validators (i.e. trusted peers) can also be updated as the blockchain runs. 

Thus, instead of a static config file, we'll need to update and save trusted peers along with known version subtrees. 

I'd suggest including initial known version subtrees (or the genesis hash when known version is 0) into `Config` struct in `config` package.

**Comment by the729** [comment]
Hi, I'm glad to announce that go-libra now supports Waypoint, a new way to specify initial trust. 

See the [docs](https://godoc.org/github.com/the729/go-libra/client#New) for using Waypoint in go-libra. And [detailed docs about Waypoint](https://github.com/libra/libra/issues/1384) in libra system. The examples in this project is also a good starting point.

In short, you can specify a known trusted waypoint when creating a client instance. The current testnet waypoint is "0:59d76f0cb85470b269e754b54edac5d88619f21234d69e02ce85cea6f003089a".

If you don't know the waypoint, you can also set it to "insecure" (which means you trust the ledger responses anyway), and later retrieve a waypoint by calling `client.GetLatestWaypoint()`.

Waypoint eliminates the need for trusted peers as well as genesis hash. So I'm going to close this issue. Please feel free to respond if you have any questions.
